import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'


export default function Home() {
  const router = useRouter();
  const usersClick = (e) => {
    e.preventDefault();
    router.push("users");
  }

  const doorsClick = (e) => {
    e.preventDefault();
    router.push("doors");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Panel administratora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Panel administratora
        </h1>

        <div className={styles.grid}>
          <a href="users.js" onClick={usersClick} className={styles.card}>
            <h2>Zarządzanie użytkownikami</h2>
            <p>Dodawaj i usuwaj użytkowników z systemu</p>
          </a>

          <a href="doors.js" onClick={doorsClick} className={styles.card}>
            <h2>Zarządzanie drzwiami i uprawnieniami </h2>
            <p>Dodawaj i usuwaj drzwi z systemu oraz nadawaj użytkownikom uprawnienia do pomieszczeń!</p>
          </a>

        </div>
      </main>
    </div>
  )
}


