import Head from 'next/head'
import React from 'react'
import styles from '../styles/User.module.css'
import { useState } from 'react'
const io = require("socket.io-client");

const socket = io.connect("http://localhost:4000", {
    transports: ['websocket'],
    upgrade: false
});

socket.on('deleteUserRes', function (data) {
    if (data.error=="true") {
        deleteUser(data.email)
        alert('Podano następujący email: ' + data.email + ' \n \n Usuwanie zakończyło się sukcesem');
    } else {
        alert('Podano następujący email: ' + data.email + ' \n \n Usuwanie zakończyło się niepowodzeniem');
    }
});

socket.on('addUserRes', function (data) {
    if (data.error === "true") {
        alert('Podano następujący email: ' + data.email +' haslo: '+ data.password + '\n \n Dodanie zakończyło się sukcesem');
        addUser(data.email,data.password);
    } else {
        alert('Podano następujący email: ' + data.email +' haslo: '+ data.password + '\n \n Dodanie zakonczyło się niepowodzeniem');
    }
});

class User {
    constructor(email, pass) {
        this.email = email;
        this.password = pass;
    }
}

function pullUsers() {
//i no nothing john snow
}

var users = [new User("test@gmail.com", "12345678"), new User("test@gmail.com", "12345678"),
new User("xd@lol.com", "123"), new User("asdlasdo@sfsl.com", "12asdad3")];

function userForceUpdate() {
    const [value, setValue] = useState(0);
    return () => setValue(value => value + 1);
}

function UserTable(props) {

    var index = 1;
    return (
        <div className={styles.table}>
            <div className={styles.tableheader}>
                <div className={styles.headerItem}>Lp.</div>
                <div className={styles.headerItem}>Email</div>
                <div className={styles.headerItem}>Password</div>
            </div>
            {props.items.map(item => (
                <div className={styles.tableRow} key={index}>
                    <div className={styles.tableData}>{index++}</div>
                    <div className={styles.tableData}>{item.email}</div>
                    <div className={styles.tableData}>{item.password}</div>
                </div>
            ))}
        </div>
    );
}

function addUser(email, password) {
    var newUser = new User(email, password);
    users.push(newUser);

}

function deleteUser(email) {
    var index;
    for (let i = 0; i < users.length; i++) {
        if (users[i].email == email) {
            index = i;
            break;
        }
    }
    if (index > -1) {
        users.splice(index, 1);
    }
}

export default function Main() {
    pullUsers();
    let emailInputDelete = React.createRef();
    const refresh = userForceUpdate();
    let emailInputAdd = React.createRef();
    let passwordInputAdd = React.createRef();

    function handleSubmitAdd(event) {
        event.preventDefault();
        event.stopPropagation();
        socket.emit("addUser", {email: emailInputAdd.current.value, password: passwordInputAdd.current.value});
        emailInputAdd.current.value = '';
        passwordInputAdd.current.value = '';
        refresh();
    }

    function handleSubmitDelete(event) {
        event.preventDefault();
        event.stopPropagation();
        socket.emit("deleteUser", {email: emailInputDelete.current.value});
        emailInputDelete.current.value = '';
        refresh();
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Użytkownicy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Użytkownicy
                </h1>
                <UserTable items={users}/>
                <div className={styles.box}>
                    <form className={styles.form, styles.addform} onSubmit={handleSubmitAdd}>
                        <h2>Add user</h2>
                        <input className={styles.inputtext} placeholder="Email" type="text" ref={emailInputAdd} />
                        <input className={styles.inputtext} placeholder="Password" type="password" ref={passwordInputAdd} />
                        <input className={styles.inputsubmit} type="submit" value="Add new user" />
                    </form>
                    <form className={styles.form} onSubmit={handleSubmitDelete}>
                        <h2>Delete user</h2>
                        <input ref={emailInputDelete} className={styles.inputtext} type="text" placeholder="Email" />
                        <input className={styles.inputsubmit} type="submit" value="Delete selected user" />
                     </form>
                </div>
            </main>
        </div>
    );
}
