import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/User.module.css'

class User {
    constructor(email, pass) {
        this.email = email;
        this.password = pass;
    }
}

function UserAdminPanelApp(props) {
    var users = [new User("test@gmail.com", "12345678"), new User("test@gmail.com", "12345678"),
    new User("xd@lol.com", "123"), new User("asdlasdo@sfsl.com", "12asdad3")];

    return (
        <div className={styles.container}>
            <Head>
                <title>Użytkownicy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Użytkownicy
                </h1>
                <UserTable items={users} />
                <div className={styles.box}>
                    <AddUserForm items={users} />
                    <DeleteUserForm />
                </div>
            </main>
        </div>
    );

}

function AddUserForm(props) {
    let emailInput = React.createRef();
    let passwordInput = React.createRef();

    function handleSubmit(event) {
        alert('Podano następujący email: ' + emailInput.current.value + passwordInput.current.value);
        event.preventDefault();
        emailInput.current.value = '';
        passwordInput.current.value = '';
    }


    return (
        <form className={styles.form, styles.addform} onSubmit={handleSubmit}>
            <h2>Add user</h2>
            <input className={styles.inputtext} placeholder="Email" type="text" ref={emailInput} />
            <input className={styles.inputtext} placeholder="Password" type="password" ref={passwordInput} />
            <input className={styles.inputsubmit} type="submit" value="Add new user" />
        </form>
    );

}

function DeleteUserForm(props) {
    let emailInput = React.createRef();

    function handleSubmit(event) {
        alert('Podano następujący email: ' + emailInput.current.value);
        event.preventDefault();
        emailInput.current.value = '';
    }

    return (
        <form className={styles.form} onSubmit={handleSubmit}>
            <h2>Delete user</h2>
            <input ref={emailInput} className={styles.inputtext} type="text" placeholder="Email" />
            <input className={styles.inputsubmit} type="submit" value="Delete selected user" />
        </form>
    );
}

function UserTable(props) {
    var index = 1;
    return (
        <div className={styles.table}>
            <div className={styles.tableheader}>
                <div className={styles.headerItem}>Lp.</div>
                <div className={styles.headerItem}>Email</div>
                <div className={styles.headerItem}>Password</div>
            </div>
            {props.items.map(item => (
                <div className={styles.tableRow} key={index}>
                    <div className={styles.tableData}>{index++}</div>
                    <div className={styles.tableData}>{item.email}</div>
                    <div className={styles.tableData}>{item.password}</div>
                </div>
            ))}
        </div>
    );
}

/*export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Użytkownicy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Użytkownicy
                </h1>
                <UserTable />
                <AddUserForm />
                <DeleteUserForm />
            </main>
        </div>
    )
}*/

export default function Main() {
    return (
        <UserAdminPanelApp />
    );
}
